import {readFile,mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {request as httpRequest} from 'node:http';
import {pathToFileURL} from 'node:url';
import {demo} from '../src/demo.mjs';
const playwrightModule=process.env.PLAYWRIGHT_MODULE;
const {chromium}=await import(playwrightModule?pathToFileURL(playwrightModule).href:'playwright');
const url=process.env.DASHBOARD_URL||'http://127.0.0.1:4317';
const evidenceDir=process.env.EVIDENCE_DIR||new URL('../evidence/',import.meta.url).pathname;
await mkdir(evidenceDir,{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1024}});
const page=await context.newPage();const errors=[],requests=[];const checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
async function check(name,fn){await fn();checks.push({name,result:'passed'});console.log(`PASS ${name}`);}
async function nav(name){await page.locator('#navigation').getByRole('button',{name:new RegExp('^'+name)}).click();}
async function shot(name){await page.evaluate(()=>{document.activeElement?.blur();scrollTo(0,0);});await page.evaluate(()=>new Promise(requestAnimationFrame));await page.screenshot({path:`${evidenceDir}/${name}.png`,fullPage:true});}
async function importPayload(payload){await nav('Data & safety');const input=await page.locator('#snapshot-file').elementHandle();await page.locator('#snapshot-file').setInputFiles({name:'safe-snapshot.json',mimeType:'application/json',buffer:Buffer.from(payload)});await page.waitForFunction(input=>!input.isConnected,input);}
try{
await page.goto(url);
await check('Identity, meaningful default decision view and synthetic labels',async()=>{assert.match(await page.title(),/GuardClaw/);assert.equal(new URL(page.url()).origin,url);await page.getByRole('heading',{name:'How much should the first import support?',exact:true}).waitFor();assert.equal(await page.locator('.decision-list > article').count(),2);assert.match(await page.locator('#snapshot-label').textContent(),/^Synthetic demo/);assert.match(await page.locator('#snapshot-note').textContent(),/Captured 01 Oct 2026, 10:00 UTC.*Not live/);assert.match(await page.locator('.decision-card').first().textContent(),/Recommendation.*Start with.*Why.*Trade-off.*Disagreement/s);});
await shot('desktop-decisions');
await check('Decision selection changes one proof locally; decorative motion pauses',async()=>{await page.locator('.decision-option').nth(1).click();await page.getByRole('heading',{name:'What is the smallest useful feedback trial?',exact:true}).waitFor();assert.match(await page.locator('#decision-proof').textContent(),/Ask one volunteer.*decision-002/s);assert.equal(await page.locator('.decision-proof').count(),1);await page.waitForFunction(()=>document.activeElement?.dataset.decisionId==='try-it');await page.locator('.decision-option').first().click();await page.getByRole('button',{name:'Pause decorative background',exact:true}).click();assert.equal(await page.locator('.atmosphere').evaluate(e=>getComputedStyle(e).animationPlayState),'paused');await page.getByRole('button',{name:'Resume decorative background',exact:true}).click();assert.equal(await page.locator('.atmosphere').evaluate(e=>getComputedStyle(e).animationPlayState),'running');});
await check('Task selection exposes blocker, observed timestamp and source',async()=>{await page.getByRole('button',{name:'Inspect task →'}).first().click();assert.match(await page.locator('#inspector').textContent(),/Source provenance.*Authored demo fixture/s);assert.match(await page.locator('#inspector').textContent(),/Blocker.*Owner needs/s);await page.waitForFunction(()=>document.activeElement===document.querySelector('#inspector'));assert.equal(await page.locator('#inspector').evaluate(e=>document.activeElement===e),true);});
await shot('desktop-work');
await check('Search, empty result and clear path preserve totals',async()=>{await page.getByRole('searchbox',{name:'Search work'}).fill('zz-no-match');assert.equal(await page.locator('.task-button').count(),0);await page.getByRole('heading',{name:'No matching work'}).waitFor();assert.equal(await page.locator('.metric-value').first().textContent(),'6');await page.getByRole('button',{name:'Clear filters',exact:true}).click();assert.equal(await page.locator('.task-button').count(),6);});
await check('Attention, verified and unknown/stale filters',async()=>{await page.getByLabel('Show',{exact:true}).selectOption('attention');assert.equal(await page.locator('.task-button').count(),4);assert.match(await page.locator('.task-list').textContent(),/Stale/);assert.match(await page.locator('.task-list').textContent(),/Unknown/);await page.getByLabel('Show',{exact:true}).selectOption('verified');assert.equal(await page.locator('.task-button').count(),1);assert.match(await page.locator('#inspector').textContent(),/Read-only control audit.*Passed/s);});
await check('Evidence distinguishes passed, failed and pending with date',async()=>{await nav('Evidence');assert.equal(await page.locator('.evidence-table tbody tr').count(),3);for(const text of ['Passed','Failed','Pending'])assert.equal(await page.locator('.evidence-table').getByText(text,{exact:true}).count(),1);});
await shot('desktop-evidence');
await check('Valid empty import, memory-only reset and no owner choices',async()=>{const v={schemaVersion:1,title:'Empty example',capturedAt:new Date(Date.now()-60000).toISOString().replace(/\.\d{3}Z$/,'Z'),tasks:[],decisions:[],evidence:[]};await importPayload(JSON.stringify(v));assert.match(await page.locator('#import-message').textContent(),/opened in memory/);await nav('All work');await page.getByRole('heading',{name:'No work in this snapshot'}).waitFor();assert.equal(await page.locator('.metric-value').first().textContent(),'0');await shot('empty-state');await page.getByRole('button',{name:'Reset demo',exact:true}).first().click();assert.equal(await page.locator('.task-button').count(),6);});
await check('Malformed/oversized import errors keep last good snapshot and echo no payload',async()=>{await importPayload('{unsafe raw marker');assert.match(await page.locator('#import-message').textContent(),/Invalid JSON.*preserved/);assert.doesNotMatch(await page.locator('#content').textContent(),/unsafe raw marker/);await shot('error-state');await page.locator('#snapshot-file').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(256*1024+1,120)});assert.match(await page.locator('#import-message').textContent(),/limit/);assert.equal(await page.locator('.metric-value').first().textContent(),'6');});
await check('HTML is inert text; unsafe links/secrets reject; good links remain inert',async()=>{const v=structuredClone(demo);v.tasks[0].title='<img src=x onerror=alert(1)>';v.tasks[0].source.url='https://example.com/public-check';await importPayload(JSON.stringify(v));await nav('All work');assert.equal(await page.locator('.task-title').first().textContent(),v.tasks[0].title);assert.equal(await page.locator('#content img').count(),0);assert.equal(await page.locator('a[href^="http"]').count(),0);assert.match(await page.locator('#inspector').textContent(),/example.com\/public-check \(inert\)/);v.tasks[0].source.url='javascript:alert(1)';await importPayload(JSON.stringify(v));assert.match(await page.locator('#import-message').textContent(),/rejected/);v.tasks[0].source.url='https://example.com/public-check';v.tasks[0].summary='api_key: '+'synthetic-unsafe';await importPayload(JSON.stringify(v));assert.match(await page.locator('#import-message').textContent(),/sensitive data/);assert.doesNotMatch(await page.locator('#content').textContent(),/synthetic-unsafe/);await page.getByRole('button',{name:'Reset demo',exact:true}).click();});
await check('Long imported titles and owners wrap on small screens',async()=>{const v=structuredClone(demo);v.tasks[0].title='A'.repeat(120);v.tasks[0].owner='B'.repeat(80);v.decisions[0].title='C'.repeat(120);await page.setViewportSize({width:390,height:844});await importPayload(JSON.stringify(v));await nav('Owner decisions');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await nav('All work');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'Reset demo',exact:true}).click();});
await check('Keyboard focus, skip link and responsive iPhone layouts',async()=>{await page.goto(url);await page.keyboard.press('Tab');assert.equal(await page.locator('.skip-link').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#main').evaluate(e=>e===document.activeElement),true);for(const width of [390,375]){await page.setViewportSize({width,height:844});await nav('Owner decisions');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await shot(`iphone-${width}-decisions`);await nav('All work');await page.locator('.task-button').nth(4).click();assert.match(await page.locator('#inspector').textContent(),/Stale/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(width===390)await shot('iphone-work-stale');await nav('Data & safety');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}});
await check('No runtime errors, external requests, operational mutations or persistent storage',async()=>{assert.deepEqual(errors,[]);assert.equal(requests.every(r=>new URL(r.url).origin===url&&r.method==='GET'),true);const state=await page.evaluate(async()=>({local:localStorage.length,session:sessionStorage.length,cookie:document.cookie,databases:typeof indexedDB.databases==='function'?await indexedDB.databases():[]}));assert.deepEqual(state,{local:0,session:0,cookie:'',databases:[]});assert.equal(await page.getByRole('button',{name:/^(approve|execute|merge|send|deploy)$/i}).count(),0);});
await check('Server route/method/host boundaries and CSP',async()=>{const root=await fetch(url);assert.match(root.headers.get('content-security-policy'),/connect-src 'none'/);for(const path of ['/docs/PLAN.md','/.env','/server.mjs','/src/app.mjs?x=1'])assert.equal((await fetch(url+path)).status,path.includes('?')?400:404);assert.equal((await fetch(url,{method:'POST',body:'x'})).status,405);assert.equal(await new Promise((resolve,reject)=>{const req=httpRequest(url,{headers:{Host:'example.com'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();}),403);});
if(process.env.AXE_PATH){await page.setViewportSize({width:1440,height:1024});for(const name of ['Owner decisions','All work','Evidence','Data & safety']){await nav(name);await page.evaluate(await readFile(process.env.AXE_PATH,'utf8'));const result=await page.evaluate(async()=>await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));checks.push({name:`axe ${name}`,result:result.violations.length?'failed':'passed',violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});assert.deepEqual(result.violations.map(x=>x.id),[]);console.log(`PASS axe ${name}`);}}
const report={observedAt:new Date().toISOString(),browser:browser.version(),browserPath:'Installed Playwright Chromium scripted QA; primary interactive IAB verification recorded separately',viewports:['1440×1024','390×844','375×844'],checks,requests:requests.length,externalRequests:requests.filter(r=>new URL(r.url).origin!==url).length,errors,limits:['No real iPhone/Safari/VoiceOver testing','No authenticated source verification','Credential detection partial','No live adapter/GuardClaw enforcement']};await writeFile(`${evidenceDir}/browser-results.json`,JSON.stringify(report,null,2)+'\n');
}catch(error){await shot('failure');await writeFile(`${evidenceDir}/browser-failure.json`,JSON.stringify({error:error.message,checks,errors},null,2)+'\n');throw error;}finally{await browser.close();}
