import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {demo} from '../src/demo.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const url=process.env.DASHBOARD_URL||'http://127.0.0.1:4317',out=process.env.EVIDENCE_DIR||new URL('../evidence/scanner/',import.meta.url).pathname;
await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1024}}),checks=[],errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
const fixture=async name=>JSON.parse(await readFile(new URL('../../schemas/fixtures/'+name,import.meta.url),'utf8'));
async function check(name,fn){await fn();checks.push({name,result:'passed'});console.log('PASS '+name);}
async function safety(){await page.locator('#navigation').getByRole('button',{name:'Data & safety',exact:true}).click();}
async function context(){await page.getByRole('button',{name:'Prepare local scan',exact:true}).click();const text=await page.locator('#scan-command').inputValue(),m=text.match(/--snapshot-id ([0-9a-f-]{36}) --revision (\d+)/);assert.ok(m);return {snapshot_id:m[1],revision:Number(m[2])};}
async function report(r){await safety();const input=await page.locator('#scan-report-file').elementHandle();await page.locator('#scan-report-file').setInputFiles({name:'advisory.json',mimeType:'application/json',buffer:Buffer.from(typeof r==='string'?r:JSON.stringify(r))});await page.waitForFunction(e=>!e.isConnected,input);}
async function snapshot(value){await safety();const input=await page.locator('#snapshot-file').elementHandle();await page.locator('#snapshot-file').setInputFiles({name:'snapshot.json',mimeType:'application/json',buffer:Buffer.from(value)});await page.waitForFunction(e=>!e.isConnected,input);}
async function shot(name){await page.locator('#scan-panel').scrollIntoViewIfNeeded();await page.evaluate(()=>document.activeElement?.blur());await page.screenshot({path:out+'/'+name+'.png'});}
try{
 await page.goto(url);await safety();const first=await context();const originalMetrics=await page.locator('#metrics').textContent();
 await check('Manual preparation and unknown empty report state; no runner route',async()=>{assert.equal(first.revision,0);assert.match(await page.locator('#scan-panel').textContent(),/No advisory report supplied.*unknown/s);assert.match(await page.locator('#scan-command').inputValue(),/^\.\/bin\/guardclaw-report/);for(const path of ['/guardclaw/guardclaw-report','/guardclaw/go.mod','/guardclaw/schemas/guardclaw-scan-report.v1.json'])assert.equal((await fetch(url+path)).status,404);assert.equal((await fetch(url+'/scan',{method:'POST',body:'x'})).status,405);});
 let good=await fixture('complete-no-match.json');good.subject=first;
 await check('Matching no-match stays current and unverified; task evidence/totals unchanged',async()=>{await report(good);const text=await page.locator('#scan-report').textContent();assert.match(text,/Current input revision · unverified/);assert.match(text,/Safety and task verification remain unknown/);assert.match(text,/Reported start.*Reported finish.*Imported.*Coverage/s);assert.match(text,/Stale reported timestamp/);assert.equal(await page.locator('#metrics').textContent(),originalMetrics);await page.locator('#navigation').getByRole('button',{name:'All work',exact:true}).click();assert.equal(await page.locator('.task-button').count(),6);assert.equal(await page.locator('.task-button .tag.verified').count(),1);await safety();});
 await check('Malicious/duplicate/invalid UTF-8/oversized replacement is rejected without echo and preserves report',async()=>{for(const payload of [JSON.stringify({...good,extra:'<img src=https://example.com onerror=alert(1)>'}),JSON.stringify(good).replace('"revision":0','"revision":0,"revision":1'),Buffer.from([0xc3,0x28]),Buffer.alloc(65537,120)]){if(Buffer.isBuffer(payload)){const input=await page.locator('#scan-report-file').elementHandle();await page.locator('#scan-report-file').setInputFiles({name:'private-name.json',mimeType:'application/json',buffer:payload});await page.waitForFunction(e=>!e.isConnected,input);}else await report(payload);assert.match(await page.locator('#scan-message').textContent(),/Report rejected/);assert.match(await page.locator('#scan-report').textContent(),/Current input revision/);assert.doesNotMatch(await page.locator('#scan-panel').textContent(),/<img|example.com|private-name/);assert.equal(await page.locator('#scan-panel a,#scan-panel img').count(),0);}});
 await check('Rejected snapshot preserves context; identical replacement advances revision, report becomes earlier',async()=>{await snapshot('{bad');assert.deepEqual(await context(),first);await snapshot(JSON.stringify(demo));const next=await context();assert.equal(next.snapshot_id,first.snapshot_id);assert.equal(next.revision,first.revision+1);assert.match(await page.locator('#scan-report').textContent(),/Earlier input revision · stale association, unverified/);});
 await check('Mismatch/future revision and metadata-null stay unattached',async()=>{const c=await context();for(const subject of [{...c,snapshot_id:'00000000-0000-4000-8000-000000000001'},{...c,revision:c.revision+1}]){await report({...good,subject});assert.match(await page.locator('#scan-report').textContent(),/Different snapshot or future revision · unattached, unverified/);}await report(await fixture('failed-invalid-metadata.json'));assert.match(await page.locator('#scan-report').textContent(),/Metadata failure · unattached.*Unknown.*INVALID_METADATA/s);});
 await check('Failure/no-content/finding reports preserve unknown and explicit advisory severity/coverage',async()=>{const c=await context();for(const name of ['failed-timeout.json','no-content.json']){const r=await fixture(name);r.subject=c;await report(r);assert.match(await page.locator('#scan-report').textContent(),/Unknown.*Outcome remains unknown/s);}const r=await fixture('actual-at-sign-ids.json');r.subject=c;await report(r);assert.match(await page.locator('#scan-report').textContent(),/Review is needed; no action is authorized/);assert.match(await page.locator('.scan-findings').textContent(),/@/);assert.equal(await page.locator('#metrics').textContent(),originalMetrics);await shot('desktop-scanner-report');});
 await check('Scanner panel wraps and passes axe at desktop/phone, keyboard and 44px buttons',async()=>{for(const width of [1440,390,375]){await page.setViewportSize({width,height:width===1440?1024:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'Prepare local scan',exact:true}).click();assert.equal(await page.locator('#scan-command').evaluate(e=>e===document.activeElement),true);const sizes=await page.locator('#scan-panel button').evaluateAll(es=>es.map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));assert.ok(sizes.every(s=>s.width>=44&&s.height>=44));if(process.env.AXE_PATH){await page.evaluate(await readFile(process.env.AXE_PATH,'utf8'));const a=await page.evaluate(async()=>await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.deepEqual(a.violations.map(v=>v.id),[]);checks.push({name:'axe scanner '+width,result:'passed',incomplete:a.incomplete.map(v=>v.id)});}if(width===390)await shot('iphone-scanner-report');}});
 await check('Reset cancels pending report reads, discards reports and advances revision',async()=>{const before=await context();await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){if(this.name==='pending.json')return new Promise(resolve=>{window.releaseReport=async()=>resolve(await original.call(this));});return original.call(this);};});await page.locator('#scan-report-file').setInputFiles({name:'pending.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...good,subject:before}))});await page.waitForFunction(()=>typeof window.releaseReport==='function');await page.getByRole('button',{name:'Reset demo',exact:true}).click();await page.evaluate(()=>window.releaseReport());await page.waitForTimeout(100);assert.equal(await page.locator('#scan-report').count(),0);assert.equal((await context()).revision,before.revision+1);assert.equal(await page.locator('#metrics').textContent(),originalMetrics);});
 await check('Remove and reload discard report memory; new session UUID; no runtime/network/storage/action authority',async()=>{const before=await context();await report({...good,subject:before});await page.getByRole('button',{name:'Remove advisory report',exact:true}).click();assert.equal(await page.locator('#scan-report').count(),0);await report({...good,subject:before});await page.reload();await safety();const next=await context();assert.notEqual(next.snapshot_id,before.snapshot_id);assert.equal(next.revision,0);assert.equal(await page.locator('#scan-report').count(),0);assert.deepEqual(errors,[]);assert.ok(requests.every(r=>new URL(r.url).origin===url&&r.method==='GET'));assert.deepEqual(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length,cookie:document.cookie})),{local:0,session:0,cookie:''});assert.equal(await page.getByRole('button',{name:/^(approve|execute|merge|send|deploy|scan now)$/i}).count(),0);});
 await writeFile(out+'/results.json',JSON.stringify({observedAt:new Date().toISOString(),checks,errors,externalRequests:requests.filter(r=>new URL(r.url).origin!==url).length,requests:requests.length,limits:['Chromium emulation only','No physical iPhone/Safari/VoiceOver','No OS network-containment guarantee','No authenticated report provenance']},null,2)+'\n');
}catch(e){await page.screenshot({path:out+'/failure.png'});await writeFile(out+'/failure.json',JSON.stringify({error:e.message,checks,errors},null,2));throw e;}finally{await browser.close();}
