import {receiptPanel,resetReceipts} from './receipt-panel.mjs';
import {demo,DEMO_TIME} from './demo.mjs';
import {parseReport,assessReport,REPORT_LIMIT} from './guardclaw-report.mjs';
import {validateSnapshot,parseSnapshot,freshness,filterTasks,totals,MAX_BYTES,STALE_MINUTES} from './model.mjs';
import {parseLocalAccess,ACCESS_BYTES} from './local-access.mjs';
let snapshot=validateSnapshot(demo,DEMO_TIME), mode='demo', referenceTime=DEMO_TIME, view='decisions', selectedId='safe-import', selectedDecisionId='minimal-schema', search='', filter='all', importMessage='', importError=false;
const scanContext={snapshot_id:crypto.randomUUID(),revision:0};
let reportAttachment=null,scanPrepared=false,scanMessage='',scanError=false,snapshotImportGeneration=0,reportImportGeneration=0;
let liveConnected=false,liveGeneration=0,liveTimer=null,liveRequest=null,liveText='',liveMessage='',liveReceivedAt=null;
let accessCapability=null,accessGeneration=0,accessMessage='';
const liveAvailable=document.body.dataset.localFeed==='available';
const $=id=>document.getElementById(id);
function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function append(parent,...children){children.filter(Boolean).forEach(c=>parent.append(c));return parent;}
function button(text,cls,fn){const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;}
function dateText(value){return value?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'UTC'}).format(new Date(value))+' UTC':'Unknown';}
function announce(text){$('announcement').textContent=text;}
const label={proposed:'Proposed',implemented:'Implemented',verified:'Verified',active:'Active',planned:'Planned',blocked:'Blocked',done:'Done',unknown:'Unknown',fresh:'Fresh',stale:'Stale',passed:'Passed',failed:'Failed',pending:'Pending','awaiting-owner':'Awaiting owner',resolved:'Resolved'};
function tag(value){return el('span',`tag ${value}`,label[value]||value);}
function observation(record){return append(el('div','detail-line'),tag(freshness(record.observedAt,referenceTime)),el('span','',` Observed ${dateText(record.observedAt)}`));}
function sourceInfo(record){const s=record.source;const dl=el('dl','provenance');for(const [key,value] of [['Source',s.label],['Type',s.kind],['Record',s.recordId],['Observed',dateText(record.observedAt)]])append(dl,el('dt','',key),el('dd',key==='Record'?'record-id':'',value));if(s.url)append(dl,el('dt','','Reference'),el('dd','safe-reference',`${s.url} (inert)`));return dl;}
function textSection(title,text){const wrap=el('div','');append(wrap,el('h3','section-label',title),el('p','',text));return wrap;}
function empty(title,text,action){return append(el('div','empty'),el('h2','',title),el('p','',text),action);}
function evidenceItems(items){const list=el('ul','evidence-list');items.forEach(e=>{const li=el('li','evidence-item');append(li,append(el('div','row-top'),el('strong','',e.title),tag(e.result)),el('p','',e.summary),observation(e),el('p','',`${e.source.label} · ${e.source.kind} · ${e.source.recordId}`));if(e.source.url)append(li,el('p','safe-reference',`${e.source.url} (inert)`));list.append(li);});return list;}
function recommendation(d){return append(el('div','recommendation'),el('h3','section-label','Recommendation'),el('p','',d.recommendation));}
function decisionFields(d){const box=el('div','decision-fields');append(box,textSection('Why',d.rationale),textSection('Trade-off',d.tradeoffs),textSection('Disagreement',d.disagreement||'None recorded.'));return box;}
function showTask(id){selectedId=id;view='work';search='';filter='all';render();requestAnimationFrame(()=>{$('inspector')?.focus();if(innerWidth<=650)$('inspector')?.scrollIntoView({behavior:'auto',block:'start'});});}
function renderNav(){for(const [key,name] of [['decisions','Owner decisions'],['work','All work'],['evidence','Evidence'],['safety','Data & safety']]){const b=button(name,'nav-button',()=>{view=key;render();});b.dataset.view=key;$('navigation').append(b);}}
function titleBlock(title,subtitle,cls='view-heading'){const box=el('div',cls);const h=el('h1');h.id='page-title';h.textContent=title;const sub=el('p','',subtitle);sub.id='page-subtitle';return append(box,h,sub);}
function renderHeader(){const count=totals(snapshot);document.querySelectorAll('.nav-button').forEach(b=>{b.removeAttribute('aria-current');if(b.dataset.view===view)b.setAttribute('aria-current','page');b.querySelector('.nav-count')?.remove();if(b.dataset.view==='decisions'&&count.decisions)b.append(el('span','nav-count',String(count.decisions)));});
 $('snapshot-label').textContent=`${mode==='demo'?'Synthetic demo':mode==='live'?'Local feed · unverified claims':'Imported snapshot'} · ${snapshot.title}`;
 $('snapshot-note').textContent=mode==='demo'?`Captured ${dateText(snapshot.capturedAt)} · Not live. Authored examples; freshness uses this frozen time.`:`Captured ${dateText(snapshot.capturedAt)} · evaluated ${dateText(new Date(referenceTime).toISOString())}. Imported claims; no live connection. Recheck manually.`;
 if(mode==='live')$('snapshot-note').textContent=`Producer capture ${dateText(snapshot.capturedAt)} · received ${dateText(liveReceivedAt)} · evaluated ${dateText(new Date(referenceTime).toISOString())}. Claimed checks; no authenticated agent identity or execution proof.`;
 $('local-feed-status').hidden=!liveMessage;$('local-feed-status').textContent=liveMessage;
 $('metrics').replaceChildren();for(const [value,title,cls] of [[count.tasks,'tasks',''],[count.blocked,'blocked','rust'],[count.decisions,'owner decisions','rust'],[count.verified,'reported verified','teal']])$('metrics').append(append(el('div','metric'),el('span',`metric-value ${cls}`,String(value)),el('span','metric-label',title)));
 const band=$('snapshot-work');band.replaceChildren();const sample=snapshot.tasks.filter(t=>t.id==='mobile-layout'||t.id==='adapter-shape');const shown=sample.length?sample:snapshot.tasks.slice(0,2);if(shown.length){append(band,append(el('div','work-band-header'),el('span','','Work'),el('span','','Stage'),el('span','','Observed')));for(const t of shown){const fresh=freshness(t.observedAt,referenceTime);const time=t.observedAt?new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'}).format(new Date(t.observedAt))+' UTC':'Unknown';append(band,append(el('div','work-band-row'),button(t.title,'',()=>showTask(t.id)),el('span','',label[t.stage]),el('span',fresh==='stale'?'band-stale':'',`${time}${fresh==='stale'?' · Stale':''}`)));}}
}
function renderWork(){const toolbar=el('div','toolbar');const searchLabel=el('label','field search-field','Search work');const input=el('input');input.type='search';input.id='work-search';input.placeholder='Task, owner, or blocker';input.value=search;input.addEventListener('input',()=>{search=input.value;renderResults();});append(searchLabel,input);const filterLabel=el('label','field','Show');const select=el('select');select.id='work-filter';select.setAttribute('aria-label','Show');for(const [value,text] of [['all','All work'],['attention','Needs attention'],['proposed','Proposed'],['implemented','Implemented'],['verified','Verified']]){const option=el('option','',text);option.value=value;select.append(option);}select.value=filter;select.addEventListener('change',()=>{filter=select.value;renderResults();});append(filterLabel,select);append(toolbar,searchLabel,filterLabel);
 const layout=el('div','work-layout');const listArea=el('section');listArea.id='list-area';listArea.setAttribute('aria-label','Work list');const inspect=el('section','inspector');inspect.id='inspector';inspect.tabIndex=-1;inspect.setAttribute('aria-label','Task inspector');append(layout,listArea,inspect);append($('content'),toolbar,layout);renderResults();}
function renderResults(){const tasks=filterTasks(snapshot,{search,filter,referenceTime});if(!tasks.some(t=>t.id===selectedId))selectedId=tasks[0]?.id||null;const area=$('list-area');area.replaceChildren(append(el('div','list-heading'),el('h2','','Parallel work'),el('span','result-count',`${tasks.length} of ${snapshot.tasks.length} shown`)));
 if(!tasks.length){area.append(empty(snapshot.tasks.length?'No matching work':'No work in this snapshot',snapshot.tasks.length?'Try a different search or filter.':'A valid empty snapshot has no tasks, decisions, or evidence.',snapshot.tasks.length?button('Clear filters','secondary',()=>{search='';filter='all';render();}):button('Reset demo','secondary',reset)));}
 else{const list=el('ul','task-list');for(const t of tasks){const b=button('','task-button',()=>{selectedId=t.id;renderResults();requestAnimationFrame(()=>{$('inspector').focus();if(innerWidth<=650)$('inspector').scrollIntoView({behavior:'auto',block:'start'});});});b.dataset.taskId=t.id;b.setAttribute('aria-pressed',String(t.id===selectedId));b.setAttribute('aria-controls','inspector');append(b,append(el('div','row-top'),append(el('div'),el('span','task-title',t.title),el('div','task-owner',t.owner)),el('span','task-progress',t.progress?`${t.progress.completed}/${t.progress.total} steps`:'Progress unknown')));const tags=append(el('div','row-tags'),tag(t.status),tag(t.stage),tag(freshness(t.observedAt,referenceTime)));if(snapshot.decisions.some(d=>d.taskId===t.id&&d.status==='awaiting-owner'))tags.append(tag('awaiting-owner'));b.append(tags);list.append(append(el('li'),b));}area.append(list);}
 renderInspector(snapshot.tasks.find(t=>t.id===selectedId));announce(`${tasks.length} tasks shown.`);}
function renderInspector(t){const p=$('inspector');p.replaceChildren();if(!t){append(p,el('h2','','Select a task'),el('p','summary','Task context and reported evidence appear here.'));return;}
 append(p,el('span','section-label','Task context'),el('h2','',t.title),el('p','summary',t.summary),append(el('div','row-tags'),tag(t.status),tag(t.stage)),observation(t));
 if(t.blocker)append(p,append(el('div','blocker'),el('strong','','Blocker'),el('p','',t.blocker)));
 const ds=snapshot.decisions.filter(d=>d.taskId===t.id&&d.status==='awaiting-owner');for(const d of ds){const s=el('section','inspector-section');append(s,append(el('div','row-top'),el('h3','','Owner decision'),tag(d.status)),el('p','',d.title),recommendation(d),append(el('div','inspector-section'),decisionFields(d)),sourceInfo(d));p.append(s);}
 append(p,append(el('section','inspector-section'),el('h3','','Next step'),el('p','',t.nextStep),el('p','detail-line',t.progress?`Checklist: ${t.progress.completed} of ${t.progress.total} steps reported complete.`:'Progress is unknown. No percentage is inferred.')));
 const evidence=snapshot.evidence.filter(e=>e.taskId===t.id);append(p,append(el('section','inspector-section'),el('h3','','Verification evidence'),evidence.length?evidenceItems(evidence):el('p','detail-line','No check evidence supplied.')));
 append(p,append(el('section','inspector-section'),el('h3','','Source provenance'),sourceInfo(t),el('p','detail-line','Producer supplied. Source identity and claim accuracy are not authenticated by this app.')));}
function decisionCard(d){const t=snapshot.tasks.find(t=>t.id===d.taskId);const card=el('article','decision-card');append(card,append(el('div','row-top'),el('span','section-label',t.title),tag(d.status)),el('h2','',d.title));const rec=el('div');append(rec,recommendation(d),el('p','detail-line',`Task: ${label[t.status]} · ${label[t.stage]} · ${t.progress?`${t.progress.completed}/${t.progress.total} checklist steps`:'progress unknown'}`));if(t.blocker)append(rec,append(el('div','blocker'),el('strong','','Blocker'),el('p','',t.blocker)));const evidence=snapshot.evidence.filter(e=>e.taskId===t.id);append(rec,el('p','detail-line',evidence.length?`Supporting checks: ${evidence.map(e=>`${e.title} (${e.result})`).join('; ')}.`:'Supporting checks: none supplied.'));append(card,append(el('div','decision-body'),rec,decisionFields(d)));if(d.outcome)append(card,append(el('div','inspector-section'),textSection('Recorded outcome',d.outcome)));
 append(card,append(el('div','decision-bottom'),append(el('div'),observation(d),el('p','',`${d.source.label} · ${d.source.kind} · ${d.source.recordId}`)),button('Inspect task →','text-button',()=>showTask(d.taskId))));if(d.source.url)card.append(el('p','safe-reference',`${d.source.url} (inert)`));return card;}
function decisionProof(d,index){const t=snapshot.tasks.find(t=>t.id===d.taskId);const card=el('article','decision-card decision-proof');card.id='decision-proof';card.setAttribute('aria-label','Selected owner decision');append(card,append(el('div','row-top'),el('span','proof-index',`DECISION ${String(index+1).padStart(2,'0')}`),tag(d.status)),el('h2','','Recommendation & evidence'),recommendation(d),decisionFields(d));if(t.blocker)append(card,el('p','proof-blocker',t.blocker));const evidence=snapshot.evidence.filter(e=>e.taskId===t.id);append(card,append(el('section','proof-evidence'),el('h3','section-label','Evidence'),evidence.length?evidenceItems(evidence):el('p','','No supporting checks supplied.')));append(card,append(el('div','decision-bottom'),append(el('div'),observation(d),el('p','',`${d.source.label} · ${d.source.kind} · ${d.source.recordId}`)),button('Inspect task →','inspect-button',()=>showTask(d.taskId))));if(d.source.url)card.append(el('p','safe-reference',`${d.source.url} (inert)`));return card;}
function renderDecisions(){const pending=snapshot.decisions.filter(d=>d.status==='awaiting-owner');if(!pending.some(d=>d.id===selectedDecisionId))selectedDecisionId=pending[0]?.id||null;const d=pending.find(d=>d.id===selectedDecisionId);
 if(!d){append($('content'),titleBlock('Nothing awaiting the owner','This snapshot has no pending owner decisions.'),empty('No pending choices','Inspect the work and its reported evidence.',button('Inspect all work','secondary',()=>{view='work';render();})));}
 else{const hero=el('section','decision-hero');hero.setAttribute('aria-label','Owner decisions');const left=titleBlock(d.title,`${pending.length} ${pending.length===1?'choice awaits':'choices await'} you. Review the recommendation, its trade-off and the source age.`,'decision-editorial');const heading=left.querySelector('h1');const words=d.title.split(' ');if(words.length>3){heading.replaceChildren(el('span','',words.slice(0,3).join(' ')+' '),el('span','accent',words.slice(3).join(' ')));}const choices=el('div','decision-list');choices.setAttribute('role','group');choices.setAttribute('aria-label',`${pending.length} decisions awaiting owner`);pending.forEach((item,i)=>{const task=snapshot.tasks.find(t=>t.id===item.taskId);const row=el('article','decision-choice');const b=button('','decision-option',()=>{selectedDecisionId=item.id;render();requestAnimationFrame(()=>{Array.from(document.querySelectorAll('.decision-option')).find(b=>b.dataset.decisionId===item.id)?.focus();});});b.dataset.decisionId=item.id;b.setAttribute('aria-pressed',String(item.id===d.id));b.setAttribute('aria-controls','decision-proof');append(b,el('span','choice-arrow',item.id===d.id?'→':''),el('span','choice-number',String(i+1).padStart(2,'0')),append(el('span','choice-text'),el('span','choice-title',task.title),el('span','choice-meta',`${label[task.status]} · ${label[task.stage]}`)));append(row,b);choices.append(row);});append(hero,left,decisionProof(d,pending.indexOf(d)),choices);$('content').append(hero);}
 const resolved=snapshot.decisions.filter(d=>d.status==='resolved');if(resolved.length){const details=el('details','resolved-list');append(details,el('summary','',`${resolved.length} resolved ${resolved.length===1?'decision':'decisions'}`));resolved.forEach(d=>details.append(decisionCard(d)));$('resolved-content').append(details);}}
function renderEvidence(){if(!snapshot.evidence.length){$('content').append(empty('No verification evidence supplied','Implementation and completion labels alone are not check evidence.'));return;}append($('content'),append(el('div','view-intro'),el('h2','','Reported checks'),el('p','','Passed, failed, and pending remain distinct')));const table=el('table','evidence-table');const caption=el('caption','sr-only','Check outcomes and source provenance');const head=el('thead');const hr=el('tr');['Check / task','Result','Observed / source'].forEach(x=>{const th=el('th','',x);th.scope='col';hr.append(th);});append(head,hr);const body=el('tbody');for(const e of snapshot.evidence){const task=snapshot.tasks.find(t=>t.id===e.taskId);const tr=el('tr');append(tr,append(el('td'),el('strong','',e.title),el('p','',e.summary),button(task.title,'text-button',()=>showTask(task.id))),append(el('td'),tag(e.result),el('p','',e.result==='pending'?'Check has not completed.':'Producer-reported outcome.')),append(el('td'),observation(e),el('p','',`${e.source.label} · ${e.source.kind}`),el('p','record-id',e.source.recordId)));if(e.source.url)tr.lastChild.append(el('p','safe-reference',`${e.source.url} (inert)`));body.append(tr);}append(table,caption,head,body);$('content').append(table);}
function renderSafety(){const layout=el('div','safety-layout');const left=el('section','safety-panel');append(left,el('h2','','Open a safe snapshot'),el('p','','Only select an intentionally prepared, public-safe JSON file. Do not import session logs, prompts, memories, credentials, or private work data.'));
 const box=el('div','import-box');const file=el('input');file.type='file';file.id='snapshot-file';file.accept='.json,application/json';const l=el('label','','Choose local JSON');l.htmlFor=file.id;file.addEventListener('change',async()=>{const chosen=file.files?.[0];if(!chosen)return;stopLive();const generation=++snapshotImportGeneration;try{if(chosen.size>MAX_BYTES)throw Error('File exceeds the 256 KiB import limit.');const opened=Date.now();const next=parseSnapshot(await chosen.text(),opened);if(generation!==snapshotImportGeneration)return;if(scanContext.revision===Number.MAX_SAFE_INTEGER)throw Error('Snapshot revision limit reached. Reload first.');snapshot=next;scanContext.revision++;scanPrepared=false;mode='imported';referenceTime=opened;selectedId=snapshot.tasks[0]?.id||null;search='';filter='all';importMessage='Snapshot opened in memory. Nothing was uploaded or saved.';importError=false;render();announce(importMessage);}catch(error){if(generation!==snapshotImportGeneration)return;importMessage=`Import rejected: ${error.message} Current snapshot preserved.`;importError=true;render();$('import-message')?.focus();}});append(box,l,file,el('p','','Version 1 · max 256 KiB · 100 tasks · 100 decisions · 200 checks'),el('p','','Reloading or resetting discards imported data. Credential detection is partial; prepare and inspect the file yourself.'));append(left,box);if(importMessage){const m=el('p',importError?'import-error':'import-ok',importMessage);m.id='import-message';m.tabIndex=-1;m.setAttribute('role',importError?'alert':'status');left.append(m);}append(left,el('p','footnote','The examples/snapshot.json and examples/empty.json files are safe synthetic fixtures. Full contract: docs/IMPORT_SCHEMA.md.'));
 if(mode!=='demo')append(left,button('Recheck freshness now','secondary',()=>{referenceTime=Date.now();render();announce('Freshness recalculated from the current time.');}));
 const right=el('section','safety-panel');append(right,el('h2','','A deliberate boundary'));const list=el('ul');['Tasks and sources are declared by the snapshot producer. The app validates shape, not identity or truth.','All source URLs are inert. Imported text is rendered as text, never HTML.','No account/API credentials, accounts, telemetry, external requests, or browser persistence are used. An opted-in local feed makes same-origin loopback reads only.','Decisions are summaries for review. The UI cannot approve, execute, merge, message, or deploy anything.'].forEach(x=>list.append(el('li','',x)));append(right,list,append(el('div','boundary'),el('h3','','Freshness, explained'),el('p','',`Fresh means observed within ${STALE_MINUTES} minutes of the displayed evaluation time. Stale means older; unknown means no observation supplied. Offline imports do not poll. An explicitly connected local feed reevaluates freshness while polling.`)),append(el('div','boundary'),el('h3','','Future integrations'),el('p','','Supported account API adapters need separate authorization and tests. The opt-in local feed reads only deliberately published summaries. The optional local scanner below provides advisory reports; this dashboard is not a security gateway.')),append(el('div','boundary'),el('h3','','Try it and give feedback'),el('p','','Inspect one decision, compare its trade-off with the evidence, then find a stale task. Record what helped or confused you in docs/FEEDBACK.md. Sharing that feedback is a separate manual choice.')));append(layout,left,right);$('content').append(renderLocalFeedPanel(),layout,renderScanPanel(),receiptPanel(render));}
function renderScanPanel(){
 const panel=el('section','safety-panel scan-panel');panel.id='scan-panel';panel.setAttribute('aria-labelledby','scan-title');const heading=el('h2','','Optional local scan');heading.id='scan-title';
 append(panel,heading,el('p','','Run the included Core helper manually on explicitly selected safe local text, then open its report here. Nothing executes from this page. Demo use needs no Go or scanner.'),el('p','scan-warning','Advisory only. Reports and selected-text association are operator supplied and unverified. No-match never proves safety, passes a check, changes a task, or grants authorization. Network containment has not been verified.'));
 append(panel,button('Prepare local scan','secondary',()=>{scanPrepared=true;render();$('scan-command')?.focus();}));
 if(scanPrepared){const box=el('div','import-box');const command=el('textarea','scan-command');command.id='scan-command';command.readOnly=true;command.rows=4;command.value=`./bin/guardclaw-report --snapshot-id ${scanContext.snapshot_id} --revision ${scanContext.revision} < selected-safe-content.txt > scan.report.json`;const label=el('label','','Manual command for this input revision');label.htmlFor=command.id;append(box,label,command,el('p','scan-context',`Session snapshot ${scanContext.snapshot_id} · input revision ${scanContext.revision}`),el('p','','Build once using REPORT-QUICKSTART.md at the repository root. Replace only the synthetic input/output filenames with your selected local files. Exit 1 means findings; import that report. Exit 2 or absent/truncated output means unknown. A matching ID/revision does not authenticate the scanner or input.'));panel.append(box);}
 const box=el('div','import-box');const file=el('input');file.type='file';file.id='scan-report-file';file.accept='.json,application/json';const label=el('label','','Open local advisory report');label.htmlFor=file.id;
 file.addEventListener('change',async()=>{const chosen=file.files?.[0];if(!chosen)return;const generation=++reportImportGeneration;try{if(chosen.size>REPORT_LIMIT)throw Error('REPORT_TOO_LARGE');const report=parseReport(new Uint8Array(await chosen.arrayBuffer()));if(generation!==reportImportGeneration)return;reportAttachment={report,importedAt:new Date().toISOString()};scanMessage='Advisory report opened in memory. Its provenance remains unverified.';scanError=false;render();$('scan-message')?.focus();}catch{if(generation!==reportImportGeneration)return;scanMessage='Report rejected: invalid, unsupported, or over the 64 KiB limit. Previous advisory report preserved. Nothing from the file is echoed.';scanError=true;render();$('scan-message')?.focus();}});
 append(box,label,file,el('p','','Strict scan-report v1 · max 64 KiB · known baseline and pattern IDs only. Selected content, arbitrary fields, URLs and duplicate keys are rejected. Filename is not displayed.'));panel.append(box);
 if(scanMessage){const message=el('p',scanError?'import-error':'detail-line',scanMessage);message.id='scan-message';message.tabIndex=-1;message.setAttribute('role',scanError?'alert':'status');panel.append(message);}
 if(!reportAttachment){append(panel,el('p','scan-state','No advisory report supplied · outcome unknown.'));return panel;}
 const {report:r,importedAt}=reportAttachment,a=assessReport(r,scanContext);const states={current_unverified:'Current input revision · unverified',earlier_unverified:'Earlier input revision · stale association, unverified',mismatch_unverified:'Different snapshot or future revision · unattached, unverified',unattached_error:'Metadata failure · unattached, unverified'};
 const outcomes={no_patterns_matched:'No known patterns matched selected lines. Safety and task verification remain unknown.',review_needed:'Known patterns matched selected lines. Review is needed; no action is authorized.',unknown:'Unknown. The scan failed or no nonblank content was scanned.'};
 const card=el('div','scan-report');card.id='scan-report';append(card,el('h3','scan-state',states[a.association]),el('p','',outcomes[r.outcome]));const dl=el('dl','provenance');for(const [key,value] of [['Provenance','User-imported; scanner identity and selected content unverified'],['Status',r.status==='complete'?'Complete scan report':r.status==='no_content'?'No content scanned':'Scan failed'],['Reported start',r.started_at],['Reported finish',r.finished_at],['Imported',importedAt],['Age',a.age==='stale'?'Stale reported timestamp':a.age==='future'?'Future reported timestamp; clock unverified':'Recent reported timestamp; clock unverified'],['Revision',r.subject?String(r.subject.revision):'Unknown'],['Coverage',r.coverage.scanned_lines===null?'Unknown':`${r.coverage.scanned_lines} nonblank lines of ${r.coverage.total_lines} total; ${r.coverage.blank_lines} blank; ${r.coverage.input_bytes} input bytes`],['Engine','Declared static Core baseline '+r.engine.baseline_tree]])append(dl,el('dt','',key),el('dd','',value));card.append(dl);
 if(r.error)append(card,el('p','scan-warning',`Fixed scanner error: ${r.error.code}. Outcome remains unknown.`));
 if(r.findings.length){const list=el('ul','scan-findings');r.findings.forEach(f=>list.append(el('li','',`Selected-text line ${f.line} · ${f.severity} · engine recommendation ${f.decision} (advisory only) · ${f.pattern_ids.join(', ')}`)));card.append(list);}
 append(card,button('Remove advisory report','secondary',()=>{reportImportGeneration++;reportAttachment=null;scanMessage='Advisory report removed from memory.';scanError=false;render();$('scan-message')?.focus();}));panel.append(card);return panel;
}
function render(){renderHeader();$('content').replaceChildren();$('resolved-content').replaceChildren();if(view!=='decisions'){const headings={work:['Work at a glance','Inspect progress, blockers, and the evidence behind each claim.'],evidence:['What has been checked','Reported outcomes, their sources, and the work they support.'],safety:['Your data stays local','Import a safe snapshot or explicitly connect a local producer. Keep control of what you share.']};$('content').append(titleBlock(...headings[view]));}({work:renderWork,decisions:renderDecisions,evidence:renderEvidence,safety:renderSafety})[view]();}
function stopLive(){liveConnected=false;liveGeneration++;clearTimeout(liveTimer);liveRequest?.abort();liveRequest=null;if(mode==='live')liveMessage='Local feed disconnected. Last snapshot retained in memory; its checks remain claims.';else liveMessage='';}
function preserveFocusRender(){
 const active=document.activeElement,focusId=active?.id,decisionId=active?.dataset.decisionId,viewId=active?.dataset.view,taskId=active?.dataset.taskId;
 const selection=active?.type==='search'?[active.selectionStart,active.selectionEnd]:null;
 render();
 const target=focusId?$(focusId):Array.from(document.querySelectorAll('button')).find(b=>decisionId?b.dataset.decisionId===decisionId:viewId?b.dataset.view===viewId:taskId?b.dataset.taskId===taskId:false);
 target?.focus({preventScroll:true});if(selection&&target)target.setSelectionRange(...selection);
}
async function pollLocalFeed(generation){
 if(!liveConnected||generation!==liveGeneration)return;
 const controller=new AbortController();liveRequest=controller;
 const timeout=setTimeout(()=>controller.abort(),4000);
 try{
  const response=await fetch('/api/local-snapshot',{headers:{'X-Dot-Observatory':'local-feed','X-Dot-Observatory-Capability':accessCapability},credentials:'omit',cache:'no-store',redirect:'error',signal:controller.signal});
  if(response.status===403){
   if(!liveConnected||generation!==liveGeneration)return;
   stopLive();accessCapability=null;accessGeneration++;accessMessage='Local access rejected or expired. Select the access file from this server launch again. Last snapshot preserved.';liveMessage=accessMessage;preserveFocusRender();return;
  }
  if(!response.ok)throw Error();
  const text=await response.text(),now=Date.now(),next=parseSnapshot(text,now);
  if(!liveConnected||generation!==liveGeneration)return;
  const ageChanged=mode==='live'&&[...snapshot.tasks,...snapshot.decisions,...snapshot.evidence].some(r=>freshness(r.observedAt,referenceTime)!==freshness(r.observedAt,now));
  liveReceivedAt=new Date(now).toISOString();referenceTime=mode==='demo'?referenceTime:now;
  liveMessage='Local feed connected · polling every 1.5 seconds · producer claims remain unverified.';
  if(text!==liveText||mode!=='live'){
   if(scanContext.revision===Number.MAX_SAFE_INTEGER)throw Error();
   snapshotImportGeneration++;snapshot=next;mode='live';referenceTime=now;liveText=text;scanContext.revision++;scanPrepared=false;
   if(!snapshot.tasks.some(t=>t.id===selectedId))selectedId=snapshot.tasks[0]?.id||null;
   preserveFocusRender();
  }else if(ageChanged)preserveFocusRender();else renderHeader();
 }catch{
  if(!liveConnected||generation!==liveGeneration)return;
  const now=Date.now(),ageChanged=mode==='live'&&[...snapshot.tasks,...snapshot.decisions,...snapshot.evidence].some(r=>freshness(r.observedAt,referenceTime)!==freshness(r.observedAt,now));
  if(mode==='live')referenceTime=now;
  liveMessage='Local feed unavailable or rejected. Last snapshot preserved; producer claims remain unverified. Retrying.';
  // An error must not promote or replace the displayed claims.
  if(ageChanged)preserveFocusRender();else renderHeader();
 }finally{
  clearTimeout(timeout);
  if(generation===liveGeneration){liveRequest=null;if(liveConnected)liveTimer=setTimeout(()=>pollLocalFeed(generation),1500);}
 }
}
function connectLive(){if(!liveAvailable||!accessCapability||liveConnected)return;snapshotImportGeneration++;liveConnected=true;liveMessage='Connecting to the explicitly enabled local feed…';render();pollLocalFeed(++liveGeneration);}
function renderLocalFeedPanel(){
 const panel=el('section','safety-panel');append(panel,el('h2','','Connect a local agent producer'),el('p','','An agent can deliberately publish public-safe snapshot v1 summaries to a fixed owner-only spool. No agent session logs, account credentials, account API, or official Dots/Cowork connector is discovered.'));
 append(panel,el('p','',liveAvailable?'Select this server launch’s .observatory-local/access.json, then connect. Connecting polls only this loopback origin.':'Start with npm run start:live to enable the local feed. The default server remains offline.'),el('p','','Setup: docs/LOCAL_AGENT_SETUP.md. Try npm run demo:agent after starting the live server; it publishes four synthetic updates. Prepare and inspect your own summaries before publishing. Credential detection is partial.'));
 if(liveAvailable){
  const file=el('input');file.type='file';file.id='local-access-file';file.accept='.json,application/json';
  const label=el('label','','Choose local access file');label.htmlFor=file.id;
  file.addEventListener('change',async()=>{
   const chosen=file.files?.[0];if(!chosen)return;stopLive();accessCapability=null;const generation=++accessGeneration;
   try{if(chosen.size>ACCESS_BYTES)throw Error();const next=parseLocalAccess(new Uint8Array(await chosen.arrayBuffer()));if(generation!==accessGeneration)return;accessCapability=next;accessMessage='Local access loaded in memory. Its contents are never displayed or saved by the browser.';}
   catch{if(generation!==accessGeneration)return;accessMessage='Local access file rejected. Select this server launch’s access.json. No file contents are displayed.';}
   render();$('local-feed-toggle')?.focus();
  });
  append(panel,append(el('div','import-box'),label,file,el('p','','A fresh access file is created on each successful live launch. Select it explicitly; no capability is put in a URL or log. Same-user processes and privileged users remain trusted.')));
  if(accessMessage)append(panel,el('p','',accessMessage));
 }
 const control=button(liveConnected?'Disconnect local feed':'Connect local feed','secondary',()=>{if(liveConnected){stopLive();render();}else connectLive();});control.id='local-feed-toggle';control.disabled=!liveAvailable||!accessCapability;panel.append(control);
 append(panel,el('p','footnote','Read-only transport. Sources, completed steps, decision outcomes and checks are unauthenticated producer claims. No receipt chain is verified and no actions are executed or authorized. Reset, reload or a manual file selection stops polling.'));
 return panel;
}
function reset(){resetReceipts();stopLive();accessCapability=null;accessGeneration++;accessMessage='';snapshotImportGeneration++;reportImportGeneration++;if(scanContext.revision===Number.MAX_SAFE_INTEGER){announce('Snapshot revision limit reached. Reload first.');return;}scanContext.revision++;reportAttachment=null;scanPrepared=false;scanMessage='';scanError=false;snapshot=validateSnapshot(demo,DEMO_TIME);mode='demo';liveText='';liveMessage='';referenceTime=DEMO_TIME;selectedId='safe-import';selectedDecisionId='minimal-schema';search='';filter='all';importMessage='';importError=false;render();announce('Synthetic demo restored. Imported data discarded.');}
$('background-motion').addEventListener('click',()=>{const paused=document.body.dataset.motion!=='paused';document.body.dataset.motion=paused?'paused':'running';const control=$('background-motion');control.setAttribute('aria-label',paused?'Resume decorative background':'Pause decorative background');control.title=control.getAttribute('aria-label');control.firstChild.textContent=paused?'▷':'Ⅱ';announce(paused?'Decorative background paused.':'Decorative background resumed.');});
$('demo-reset').addEventListener('click',reset);renderNav();render();
