const source = recordId => ({label:'Authored demo fixture',kind:'synthetic',recordId});
export const DEMO_TIME = Date.parse('2026-10-01T10:00:00Z');
export const demo = {
 schemaVersion:1,title:'Parallel work · demo',capturedAt:'2026-10-01T10:00:00Z',
 tasks:[
  {id:'safe-import',title:'Define a safe snapshot import',summary:'A small public-safe contract for tasks, owner decisions, and reported checks.',owner:'Builder A',status:'blocked',stage:'proposed',progress:{completed:2,total:4},observedAt:'2026-10-01T09:56:00Z',source:source('task-001'),blocker:'Owner needs to choose between a minimal schema and extensible metadata.',nextStep:'Keep version 1 small; review the recommendation before changing scope.'},
  {id:'mobile-layout',title:'Make the inspector useful on iPhone',summary:'Preserve the work list and evidence context in a single-column layout.',owner:'Builder B',status:'active',stage:'implemented',progress:{completed:3,total:5},observedAt:'2026-10-01T09:48:00Z',source:source('task-002'),blocker:'',nextStep:'Check keyboard focus and long text at 390px.'},
  {id:'source-links',title:'Check imported source links',summary:'Validate producer references and keep all source URLs inert in the demo.',owner:'Reviewer C',status:'blocked',stage:'implemented',progress:{completed:2,total:3},observedAt:'2026-10-01T09:42:00Z',source:source('task-003'),blocker:'The illustrative encoded-path case failed its check.',nextStep:'Reject encoded paths and rerun the URL cases.'},
  {id:'read-only',title:'Separate viewing from authorization',summary:'No approval, execute, merge, or message action appears in the inspector.',owner:'Reviewer D',status:'done',stage:'verified',progress:{completed:4,total:4},observedAt:'2026-10-01T09:35:00Z',source:source('task-004'),blocker:'',nextStep:'Preserve the read-only boundary in future adapters.'},
  {id:'adapter-shape',title:'Sketch a generic adapter boundary',summary:'A future adapter may produce safe records from a supported API.',owner:'Builder A',status:'planned',stage:'proposed',progress:{completed:1,total:3},observedAt:'2026-10-01T07:14:00Z',source:source('task-005'),blocker:'',nextStep:'Refresh API feasibility before implementing any integration.'},
  {id:'feedback',title:'Collect first-use feedback locally',summary:'Try the demo with a simple written feedback template and no telemetry.',owner:'Unassigned',status:'unknown',stage:'proposed',progress:null,observedAt:null,source:source('task-006'),blocker:'',nextStep:'Find a volunteer and record their experience without personal data.'}
 ],
 decisions:[
  {id:'minimal-schema',taskId:'safe-import',title:'How much should the first import support?',status:'awaiting-owner',recommendation:'Start with the minimal version 1 schema.',rationale:'Tasks, decisions, and check records cover the first-use questions without pulling in private agent state.',tradeoffs:'Simpler review and less exposure; richer history must wait for a later version.',disagreement:'An extensible metadata field could speed adapter experiments, but makes the safe boundary harder to audit.',outcome:'',observedAt:'2026-10-01T09:56:00Z',source:source('decision-001')},
  {id:'try-it',taskId:'feedback',title:'What is the smallest useful feedback trial?',status:'awaiting-owner',recommendation:'Ask one volunteer to try the synthetic demo locally.',rationale:'A short trial can reveal whether the attention view and evidence labels answer the right questions.',tradeoffs:'No hosted setup or telemetry; the volunteer must run a local server and send feedback manually.',disagreement:'A hosted preview would reduce setup work, but publishing and naming have not been decided.',outcome:'',observedAt:'2026-10-01T09:30:00Z',source:source('decision-002')},
  {id:'view-boundary',taskId:'read-only',title:'Should viewing a decision authorize work?',status:'resolved',recommendation:'Keep operational authorization outside this dashboard.',rationale:'A snapshot cannot establish the identity, scope, or current consent required for an action.',tradeoffs:'One more step to act; a clearer boundary for people trying the demo.',disagreement:'None recorded in this authored example.',outcome:'Synthetic owner chose a read-only view.',observedAt:'2026-10-01T09:25:00Z',source:source('decision-003')}
 ],
 evidence:[
  {id:'readonly-check',taskId:'read-only',title:'Read-only control audit',result:'passed',observedAt:'2026-10-01T09:35:00Z',summary:'Illustrative check: no operational approval or execution controls found. This is synthetic evidence, not a test of this prototype.',source:source('check-001')},
  {id:'url-check',taskId:'source-links',title:'Encoded source path case',result:'failed',observedAt:'2026-10-01T09:42:00Z',summary:'Illustrative failure: an encoded source path was accepted. The demo task remains blocked until its hypothetical check is repeated.',source:source('check-002')},
  {id:'phone-check',taskId:'mobile-layout',title:'Small-screen inspection',result:'pending',observedAt:null,summary:'Illustrative check has not run. Implementation alone does not establish usability.',source:source('check-003')}
 ]
};
