// Copyright 2026 TakeInterest Inc.
// SPDX-License-Identifier: Apache-2.0
// Generate public report IDs from the single Core engine, never from another copy.
package main

import (
	"encoding/json"
	"fmt"
	"github.com/TakeInterestInc/guardclaw-core/guardian/security"
	"github.com/TakeInterestInc/guardclaw-core/guardian/tiered"
	"os"
	"sort"
)

const baseline = "a0b591985209611ffc515a9ff676cea5eab83555"

func main() {
	e, err := tiered.NewEngine(nil)
	if err != nil {
		panic("engine unavailable")
	}
	ids := map[string]bool{"GC-BLOOM-HIT": true, "GC-ENTROPY-HIGH": true}
	for _, p := range security.ExportAllPatterns() {
		ids[p.Name] = true
	}
	for i := 0; i < e.Stats().ACPatterns; i++ {
		ids[fmt.Sprintf("GC-AC-%04d", i)] = true
	}
	list := make([]string, 0, len(ids))
	for id := range ids {
		list = append(list, id)
	}
	sort.Strings(list)
	registry := struct {
		Baseline string   `json:"baseline_tree"`
		IDs      []string `json:"pattern_ids"`
	}{baseline, list}
	b, err := json.MarshalIndent(registry, "", "  ")
	if err != nil {
		panic("registry unavailable")
	}
	if err = os.WriteFile("schemas/guardclaw-pattern-ids.v1.json", append(b, '\n'), 0644); err != nil {
		panic("cannot write registry")
	}
	var legacy struct {
		Baseline string   `json:"baseline_tree"`
		IDs      []string `json:"pattern_ids"`
	}
	b, err = os.ReadFile("schemas/guardclaw-pattern-ids.legacy.v1.json")
	if err != nil || json.Unmarshal(b, &legacy) != nil {
		panic("legacy registry unavailable")
	}
	omitted := []string{}
	old := map[string]bool{}
	for _, id := range legacy.IDs {
		old[id] = true
	}
	for _, id := range list {
		if !old[id] {
			omitted = append(omitted, id)
		}
	}
	for _, id := range legacy.IDs {
		if !ids[id] {
			panic("legacy ID removal requires explicit migration")
		}
	}
	current, _ := json.Marshal(list)
	exclude, _ := json.Marshal(omitted)
	js := fmt.Sprintf("// Copyright 2026 TakeInterest Inc. SPDX-License-Identifier: Apache-2.0\n// Generated by go run ./tools/generate-registry from canonical root schemas.\nexport const BASELINE_TREE=%q;\nexport const LEGACY_BASELINE_TREE=%q;\n// gitleaks:allow public fixed pattern IDs, not credentials\nexport const PATTERN_IDS=Object.freeze(%s); // gitleaks:allow\nconst added=new Set(%s);\nexport const LEGACY_PATTERN_IDS=Object.freeze(PATTERN_IDS.filter(id=>!added.has(id)));\n", baseline, legacy.Baseline, current, exclude)
	if err = os.WriteFile("observatory/src/guardclaw-patterns.mjs", []byte(js), 0644); err != nil {
		panic("cannot write browser registry")
	}

	var schema map[string]any
	b, err = os.ReadFile("schemas/guardclaw-scan-report.v1.json")
	if err != nil || json.Unmarshal(b, &schema) != nil {
		panic("report schema unavailable")
	}
	props := schema["properties"].(map[string]any)
	engine := props["engine"].(map[string]any)["properties"].(map[string]any)["baseline_tree"].(map[string]any)
	delete(engine, "const")
	engine["enum"] = []string{baseline, legacy.Baseline}
	findings := props["findings"].(map[string]any)["items"].(map[string]any)["properties"].(map[string]any)
	findings["pattern_ids"].(map[string]any)["items"].(map[string]any)["enum"] = list
	b, err = json.MarshalIndent(schema, "", "  ")
	if err != nil || os.WriteFile("schemas/guardclaw-scan-report.v1.json", append(b, '\n'), 0644) != nil {
		panic("cannot write report schema")
	}
	fmt.Printf("Generated %d current IDs; preserved %d legacy IDs.\n", len(list), len(legacy.IDs))
}
